#!/bin/bash

# determine how and where to install new files in the main folder structure.

mkdir -p ../../seeder ../../seeder/models ../../seeder/updates ../../seeder/data

cp -Rn updates/* ../../seeder/updates
cp -Rn data/* ../../seeder/data
cp -n template.js ../../seeder
